// Command cover generates a coverage-directed conformance corpus.
//
//	go run ./cmd/cover -out ../../work/corpus
//
// For each behaviour of the machine it can reach, it emits the smallest
// trace that exercises it, in three files:
//
//	NNN-<name>.ndjson         external events only — the recorded-trace wire
//	                          format, consumed unchanged by `lincheck` and
//	                          `lake exe checktrace`
//	NNN-<name>.driven.ndjson  the same run with its internal steps in place,
//	                          for a harness that can drive the server's loop
//	NNN-<name>.json           what the wire format cannot carry: the
//	                          behaviour witnessed, and the expected outbox
//
// plus INDEX.md, the coverage report.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	model "github.com/resonatehq/resonate-specification/valid/porc"
)

func main() {
	out := flag.String("out", "corpus", "output directory")
	seeds := flag.Int("seeds", 400, "random scripts to search after the templates")
	disc := flag.String("discipline", "m", "read discipline to generate against: p or m")
	flag.Parse()

	d := model.Materialized
	if *disc == "p" {
		d = model.Projected
	}

	c := model.BuildCorpus(d, *seeds)

	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "cover:", err)
		os.Exit(1)
	}
	// A regenerated corpus replaces the old one; leaving stale cases behind
	// would make the index lie about what is in the directory.
	old, _ := filepath.Glob(filepath.Join(*out, "*"))
	for _, f := range old {
		os.Remove(f)
	}

	covered := map[string]bool{}
	for i, cs := range c.Cases {
		stem := filepath.Join(*out, fmt.Sprintf("%03d-%s", i+1, trim(cs.Name)))
		// No empty .ndjson for a driven-only case: a zero-byte trace is not
		// a trace, and writing one would hand the implementor a file that
		// every checker rejects as a parse error.
		if body := cs.Observational(d); body != "" {
			write(stem+".ndjson", body)
		}
		write(stem+".driven.ndjson", cs.Driven(d))
		write(stem+".json", cs.Sidecar())
		for _, b := range cs.Covers {
			covered[b] = true
		}
	}

	var missed []string
	for _, b := range c.Buckets {
		if !covered[b] {
			missed = append(missed, b)
		}
	}
	// Residue against the DECLARED domain, which is the only kind the search
	// cannot report for itself: a behaviour it never reached looks exactly
	// like one that does not exist.
	var undeclared []string
	for _, b := range model.Declared {
		if !covered[b] {
			undeclared = append(undeclared, b)
		}
	}
	sort.Strings(missed)
	sort.Strings(undeclared)

	write(filepath.Join(*out, "INDEX.md"), index(c, missed, undeclared))

	fmt.Printf("%d cases, %d behaviours covered", len(c.Cases), len(covered))
	if len(missed) > 0 {
		fmt.Printf(", %d LOST IN MINIMIZATION", len(missed))
	}
	fmt.Printf("\n  %d from templates, %d from search\n", c.FromTmpl, c.FromRand)
	fmt.Printf("  %d cases run in both tiers, %d need a driveable internal loop\n",
		len(c.Cases)-c.DrivenOnly, c.DrivenOnly)
	if len(undeclared) > 0 {
		fmt.Printf("  %d declared behaviours NEVER REACHED: %s\n",
			len(undeclared), strings.Join(undeclared, ", "))
	}
	fmt.Printf("  written to %s\n", *out)
}

func trim(s string) string {
	if len(s) > 72 {
		return s[:72]
	}
	return s
}

func write(path, body string) {
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "cover:", err)
		os.Exit(1)
	}
}

func index(c *model.Corpus, missed, undeclared []string) string {
	var b strings.Builder
	b.WriteString("# Conformance corpus\n\n")
	b.WriteString("Generated by `go run ./cmd/cover`. Do not edit by hand — regenerate.\n\n")
	fmt.Fprintf(&b, "%d cases covering %d behaviours of the machine.\n\n", len(c.Cases), len(c.Buckets))

	b.WriteString("## How to run these\n\n")
	b.WriteString("Each case is three files:\n\n")
	b.WriteString("| file | contents |\n|---|---|\n")
	b.WriteString("| `NNN-….ndjson` | external events only, in the recorded-trace wire format |\n")
	b.WriteString("| `NNN-….driven.ndjson` | the same run with its internal steps in place |\n")
	b.WriteString("| `NNN-….json` | the behaviour witnessed, and the expected outbox |\n\n")
	b.WriteString("**Driven tier** — replay every row, including the `tau.*` rows, firing the\n")
	b.WriteString("named internal step at the named instant. Every response is then forced:\n")
	b.WriteString("assert equality on all of them.\n\n")
	b.WriteString("**Observational tier** — replay the `.ndjson` only, letting the server run\n")
	b.WriteString("its own internal loop. Promise-facing responses are still forced; task-facing\n")
	b.WriteString("ones are not, because the stage of the wake pipeline is visible at the task\n")
	b.WriteString("interface by design. Assert those at quiescence.\n\n")
	b.WriteString("Both tiers need a controllable clock: `now` is synthetic and the deadlines\n")
	b.WriteString("in the requests are drawn against it.\n\n")

	fmt.Fprintf(&b, "Of %d cases, %d run in both tiers and %d need a driveable internal\n",
		len(c.Cases), len(c.Cases)-c.DrivenOnly, c.DrivenOnly)
	b.WriteString("loop. The latter have no `.ndjson`: an internal step that fires with its\n")
	b.WriteString("obligation already discharged is a silent no-op, so their observational\n")
	b.WriteString("projection is empty and no request/response capture can witness them.\n\n")

	b.WriteString("## Cases\n\n")
	b.WriteString("| # | witnesses | steps | τ | tier | from |\n|---|---|---|---|---|---|\n")
	for i, cs := range c.Cases {
		fmt.Fprintf(&b, "| %03d | `%s` | %d | %d | %s | %s |\n",
			i+1, cs.Witness, cs.Steps, cs.Taus, cs.Tier, cs.From)
	}

	b.WriteString("\n## Behaviours\n\n")
	b.WriteString("A behaviour is one observable outcome class: the request kind, the status,\n")
	b.WriteString("and the pre-state facts that decided which branch produced it.\n\n")
	for _, x := range c.Buckets {
		fmt.Fprintf(&b, "- `%s`\n", x)
	}
	if len(missed) > 0 {
		b.WriteString("\n## Reached but not covered\n\n")
		for _, x := range missed {
			fmt.Fprintf(&b, "- `%s`\n", x)
		}
	}
	if len(undeclared) > 0 {
		b.WriteString("\n## Declared but never reached\n\n")
		b.WriteString("Behaviours the specification names that no script in this run reached.\n")
		b.WriteString("A gap in the corpus, or a case that needs a hand-written scenario — not\n")
		b.WriteString("something the search can report for itself.\n\n")
		for _, x := range undeclared {
			fmt.Fprintf(&b, "- `%s`\n", x)
		}
	}
	return b.String()
}
